In [6]:
import numpy as np
import imp
import w2v_ns
imp.reload(w2v_ns)

import torch
import torch.nn as nn

import pickle

In [266]:
input = torch.randn(3, 50, requires_grad=True)
target = torch.empty(3, dtype=torch.long).random_(5)
loss=negative_sampling(target,input,vocab_len=50,n=10)
loss.backward()
print(loss)

tensor([[-7.0722e-01, -2.2900e-01,  1.1376e+00,  4.8296e-01, -2.5962e+00,
         -2.0160e-01,  1.0181e+00, -3.7189e-02, -2.7295e-02,  1.3638e+00],
        [ 1.4559e+00, -9.1085e-01,  4.6479e-01,  7.5106e-01,  1.3679e+00,
          6.9926e-04,  1.0910e+00,  1.0589e-01, -5.6384e-01, -1.0696e-01],
        [-8.6513e-01,  1.8699e-01,  4.0268e-01, -5.5249e-01, -2.9471e-01,
         -4.1893e-01, -2.9043e+00,  5.6808e-01,  2.1044e-01, -8.9919e-02]],
       requires_grad=True)
tensor([1, 1, 1])
tensor(2.9464, grad_fn=<NllLossBackward>)


In [47]:
model=torch.load('./w2v_withoud_ns_epoch_17',map_location='cpu')['state_dict']
model['embedding.weight'].detach()#[a].shape

model=w2v_ns.word2vec(200)
loss=w2v_ns.negative_sampling(model,200)
x=torch.tensor([[2],[3]])
y=torch.tensor([3,4])

loss.forward(x,y)

tensor([[ 0.0443,  0.8994,  0.9289,  ...,  0.8651, -1.0831, -0.3877],
        [-0.4391,  0.0556,  0.2107,  ...,  0.4746, -0.8800,  0.2608],
        [ 1.2031,  0.5038, -0.2473,  ...,  0.5501,  0.5616,  0.8390],
        ...,
        [ 0.8200, -0.6459, -2.4103,  ..., -0.3962, -0.2266,  0.7742],
        [ 1.6269, -0.1732, -1.7579,  ...,  1.5010,  0.6049,  2.4762],
        [ 0.1077, -0.3233, -0.0716,  ..., -1.3985, -0.0217, -0.2502]])

In [4]:
nwords = torch.FloatTensor(2, 5).uniform_(1, 5).long()   

In [5]:
nwords

tensor([[4, 3, 4, 3, 4],
        [4, 1, 2, 1, 2]])

In [11]:
with open('./preprocessing//vocab_without_josa_gut_su_freq.pickle','rb') as f:
    freq=pickle.load(f)

In [28]:
import numpy as np

total=sum(freq.values())


freq.update((x, y/total) for x, y in freq.items())

with open('./preprocessing/multi_freq.pickle','wb') as f:
    pickle.dump(freq,f)


In [38]:
torch.multinomial(torch.tensor(list(freq.values())),10)

tensor([14101,  1958,   105,  1171,  1461,  1666,   932,   128, 14544,    62])

In [111]:
weights = torch.tensor([10, 10, 3, 0], dtype=torch.float) # create a tensor of weights
torch.multinomial(weights, [2,1])

TypeError: multinomial(): argument 'num_samples' (position 2) must be int, not list

In [112]:
print(len(freq))

57384
